# Generated by Django 2.1.3 on 2019-02-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=100)),
                ('sender', models.EmailField(max_length=254)),
                ('c_myself', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'ContactUs',
            },
        ),
    ]
